name: Build & Test

on:
  push:
    branches:
      - '*'
      - '*/*'
  pull_request:
    branches:    
      - '*'
      - '*/*'

concurrency:
  group: build-${{ github.ref }}
  cancel-in-progress: true

jobs:

  build-core:
    runs-on: ubuntu-latest
    timeout-minutes: 30

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Validate Gradle Wrapper
        uses: gradle/wrapper-validation-action@v1

      - name: Set up JDK 11
        uses: actions/setup-java@v3
        with:
          distribution: 'zulu'
          java-version: 11
    
      - name: Setup Gradle
        uses: gradle/gradle-build-action@v2

      - name: Build Core
        run: cd core && ./test.sh

  build-android:
    runs-on: ubuntu-latest
    timeout-minutes: 30

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Validate Gradle Wrapper
        uses: gradle/wrapper-validation-action@v1

      - name: Set up JDK 11
        uses: actions/setup-java@v3
        with:
          distribution: 'zulu'
          java-version: 11
    
      - name: Setup Gradle
        uses: gradle/gradle-build-action@v2

      - name: Install Core
        run: cd core && ./install.sh
      
      - name: Build Android
        run: cd android && ./test.sh

  build-compose:
    runs-on: ubuntu-latest
    timeout-minutes: 30

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Validate Gradle Wrapper
        uses: gradle/wrapper-validation-action@v1

      - name: Set up JDK 11
        uses: actions/setup-java@v3
        with:
          distribution: 'zulu'
          java-version: 11
    
      - name: Setup Gradle
        uses: gradle/gradle-build-action@v2

      - name: Install Core
        run: cd core && ./install.sh
      
      - name: Install Android
        run: cd android && ./install.sh

      - name: Build AndroidX Compose
        run: cd compose && ./install.sh

  build-core-macos:
    runs-on: macos-latest
    timeout-minutes: 30

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Validate Gradle Wrapper
        uses: gradle/wrapper-validation-action@v1

      - name: Set up JDK 11
        uses: actions/setup-java@v3
        with:
          distribution: 'zulu'
          java-version: 11
    
      - name: Cache build tooling
        uses: actions/cache@v2
        with:
          path: |
            ~/.gradle/caches
            ~/.konan
          key: ${{ runner.os }}-v1-${{ hashFiles('*.gradle.kts') }}

      - name: Run Core
        run: cd core && ../gradlew macosX64Test --no-daemon --stacktrace

  build-ktor:
    runs-on: ubuntu-latest
    timeout-minutes: 30

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Validate Gradle Wrapper
        uses: gradle/wrapper-validation-action@v1

      - name: Set up JDK 11
        uses: actions/setup-java@v3
        with:
          distribution: 'zulu'
          java-version: 11
    
      - name: Setup Gradle
        uses: gradle/gradle-build-action@v2

      - name: Install Core
        run: cd core && ./install.sh
      
      - name: Build Ktor
        run: cd ktor && ./test.sh
